### ISSUE TITLE
Index Numbers, Classifications (Hadamitzky, Halpern, ...) 

### ISSUE THREAD

**Issue by ChristianGruen** [mvysny/aedict#545] opened 2015-08-16 19:07 UTC
It would be great if Kanjis could be accompanied by selectable index numbers and classification codes (see e.g. Akebi or jisho.org). If I get it right, it's only possible to choose between the index numbers of Heisig. -- Thanks for your great work.

**Comment by mvysny** [comment] 2015-08-25 04:32
Hi, thanks for your suggestion. I'm not sure if I understand correctly - would you like Aedict to display the "Dictionary Indices" table for a Kanji, as shown for example here: http://jisho.org/search/%E6%9C%AC%20%23kanji ? Good idea. I am thinking some form of "Details" button under the kanji itself, which, upon clicking, will show a dialog with all information, including the "Dictionary Indices" table. Please let me know if this is acceptable.
By "selectable" you mean that those numbers should be possible to copy to the clipboard?

**Comment by ChristianGruen** [comment] 2015-08-25 06:08
…and thanks for your reply!

>  would you like Aedict to display the "Dictionary Indices" table for a Kanji, as shown for example here: http://jisho.org/search/%E6%9C%AC%20%23kanji ?

Exactly. And it would be nice to additionally see the classification code of "The Kanji Dictionary" (in my point of view, it's actually an index number, because it's unique for each character).

> I am thinking some form of "Details" button, right under the kanji itself, which, upon clicking, will show a dialog with all information, including the "Dictionary Indices" table. Please let me know if this is acceptable.
> By "selectable" you mean that those numbers should be possible to copy to the clipboard?

By "selectable" I wanted to say that the index numbers to be displayed should be chosen/restricted in the configuration, because most people only work with one or two specific dictionaries. – I like the way it's realized in Akebi (but you'll obviously be the best person to judge where it's best placed in Aedict):

![akebi](https://cloud.githubusercontent.com/assets/196589/9459771/78e742c2-4aff-11e5-8977-92f9ec94167e.png)

**Comment by mvysny** [comment] 2015-08-25 08:00
Thanks for the explanation, the Akebi approach looks very nice, I will probably copy it as-is (do you know that great artists steal? :-D ). Please wait until the next Aedict is released with this fix, we can then discuss whether the fix is to your liking or not.

**Comment by mvysny** [comment] 2015-08-27 19:09
Implemented in Aedict 3.32

**Comment by ChristianGruen** [comment] 2015-08-27 20:22
Thanks in advance! I'll give you a final reply once I've tested the feature.

**Comment by ChristianGruen** [comment] 2015-09-12 06:57
I've finally tested the feature; thanks for adding it so quickly! I have some more comments:

* [ ] If the Kanji info settings are changed (via the (i) info button), the Kanji panel is not immediately refreshed, but only after a new page is displayed.
* [ ] As the index number configuration affects all displayed Kanjis, maybe it could make sense to remove the (i) and provide a new menu entry (next to "Max Columns")?
* [ ] Could you additionally add the "Kanji and Kana, 2nd Edition" (see e.g. [jisho.org](http://jisho.org/search/%E5%85%AB%20%23kanji) or the current [kanjidi2.xml](http://www.edrdg.org/kanjidic/kanjidic2.xml.gz) XML export)?
* [ ] I didn't find "The Kanji Dictionary" Classification Code in the list. It would be great if you could add it as well (see https://github.com/mvysny/aedict/issues/545#issuecomment-134491389).
* [ ] As there are more editions of "Remembering the Kanji", "Kanji and Kana" and other books, I would suggest removing the "Dictionaries → Heisig Edition" setting and merging it with the list of index numbers. What do you think?

**Comment by mvysny** [comment] 2015-09-14 11:59
1. Yes, this is known issue. I thought that the list will not change very often so this issue will not be very annoying.
2. The problem with the menu is as follows: imagine that there are multiple kanjis shown in a list (say, all kanjis in a word). Which kanji would then the info button display the info for? Originally, the index list was displayed to the right of the kanji, so the (i) button should be located somewhere near that list as it reveals the entire list contents. Perhaps instead of the (i) button, I should have placed the (...) button at the bottom of the list...
3. Thanks for letting me know, I took the code list from some ancient kanjidic2 xml. I will add the field in the next dictionary update rotation.
4. Hmm, can you please check out which dr_type in kanjidic2.xml corresponds to the "Kanji Dictionary" Classification Code in question? Thanks!
5. The problem is that it is not clear which edition of Heisig dictionary does the "heisig" dr_type in kanjidic2.xml reference. I have another data CSV which clearly references Heisig 3 and Heisig 6, including keywords (both English and German). Unifying this will not be easy...

**Comment by ChristianGruen** [comment] 2015-09-14 13:01
2. My hint was a bit fuzzy: I think it's a good idea to display the kanji information (Stroke, Radical, Heisig, ...) to the right side of the corresponding Kanji, and I would keep it like that.. I just wondered if it really makes sense to have one or more local  :information_source: buttons, as the setting will affect the info fields of all displayed kanjis. I think it could be represented as a global menu item or even moved to the global settings. This way, it wouldn't be that visible, but on the other hand it will rarely be changed (because most people use the same printed dictionaries all the time).
4. It's represented as query code with qc_type="sh_desc" (but in contrast to the SKIP code, it's unique for each Kanji character, so it's actually an index code).
5. As far as I know, "heisig" refers to the 3rd and "heisig6" refers to the 6th edition. This works similar to e.g. the Halpern dictionary, for which "halpern_kkld" and "halpern_kkld_2ed" exists, or Hadamitzky's Kanji and Kana editions, which use the codes "sh_kk" and "sh_kk2". Does this help?

**Comment by mvysny** [comment] 2015-09-14 15:11
2. Hmm maybe you're right. But, I believe that in this case, the setting itself should be as near as possible to the thing it controls.
4. Thanks, fixed.
5. Hmm, you're right. Now that we have this configurable table, it is possible to list both Heisig values. However, the setting is also used for Quiz "Review Learning Progress" sorting so I would keep the setting for now.

**Comment by ChristianGruen** [comment] 2015-09-17 12:03
I have just tested the latest version (thanks for the quick update!), and I noticed that many index numbers and classification codes seem to be missing:

![screenshot_2015-09-17-13-59-15](https://cloud.githubusercontent.com/assets/196589/9932499/aa4d5214-5d44-11e5-812a-104b7420cc5c.png)

Maybe it's due to an outdated version of kanjidic2.xml?

**Comment by mvysny** [comment] 2015-09-17 15:07
Hmm, this is weird, please let me look at this. Are you sure that your Aedict dictionaries are updated?

**Comment by ChristianGruen** [comment] 2015-09-17 15:10
That was the reason! I've just updated the dictionaries, now all numbers and codes are correctly displayed. Thanks!

**Comment by mvysny** [comment] 2015-09-17 18:54
Sure, no problem! I'm glad that the update helped.

**Closed by mvysny** 2015-09-17 18:54 UTC
Labels: enhancement
