### ISSUE TITLE
suru verbs inflection not found

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#954] opened 2021-04-16 09:35 UTC
When looking for a suru verb with an inflection, the entry is not found.

For example, the deinflector deinflects `menshimasu` into `mensiru, mensu` and `menshiteimasu` into `mensu`, that's why the entry is not found.

<img src="https://user-images.githubusercontent.com/626863/115002046-448e3c80-9edf-11eb-86a7-ac16b0d7c528.jpg" width="300" /><img src="https://user-images.githubusercontent.com/626863/115002067-48ba5a00-9edf-11eb-9126-af9c24993e18.jpg" width="300" />

**Comment by mvysny** [comment] 2021-04-16 10:15
That sounds like a bug in the deinflection engine, could you please open a bug report at https://gitlab.com/mvysny/jputils/-/issues ?

**Comment by mvysny** [comment] 2021-04-19 11:23
Blocked by https://gitlab.com/mvysny/jputils/-/issues/1

**Comment by mvysny** [comment] 2021-06-29 09:55
Fixed in Aedict 3.50.21

**Comment by rbleuse** [comment] 2021-06-29 15:08
Hi Martin,

I updated to 3.50.21 but I don't see any changes to this issue : looking for めんします doesn't give me the entry 面する

Anything wrong between jputils and aedict ?

**Comment by mvysny** [comment] 2021-06-29 15:47
Hmm that's weird. I've just released jputils 2.1 from the newest master and that's what Aedict 3.50.21 is using, so the bug should be fixed... However I can reproduce the bug on my phone so it's definitely not fixed. Reopening, I'll investigate.

**Comment by rbleuse** [comment] 2021-06-29 23:51
It seems that v5s verbs are well found, but not vs-s :

<img src="https://user-images.githubusercontent.com/626863/123881613-0baf2100-d980-11eb-9c21-c009455c6533.jpg" width="300" /><img src="https://user-images.githubusercontent.com/626863/123881603-08b43080-d980-11eb-998f-e3a9e5f5c999.jpg" width="300" />

**Comment by mvysny** [comment] 2021-06-30 08:57
The problem was that both "suru" verb (vsi) and "noun+suru" verbs (vss) fell into the same category in jputils (InflectableWordClass.VerbSuru); Aedict then assumed that VerbSuru is "suru" only (vsi) which effectively disabled deinflection search for vss. Fixed in https://gitlab.com/mvysny/jputils/-/commit/926fc61de13f303b70d056c6a5435db2386601ed .

I've added tests for the "面します" deinflection to Aedict as well and I'm running the test suite; if all tests pass I'll release new jputils.

**Comment by mvysny** [comment] 2021-06-30 09:40
Fixed in Aedict 3.50.22

**Closed as completed by mvysny** 2021-06-30 09:40 UTC
Labels: bug, waiting for upstream
