### ISSUE TITLE
Checkbox hard to see in 4.0.4 dark theme

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#697] opened 2016-08-18 16:39 UTC
On Android 4.0.4, the "+-2 strokes"checkbox is difficult to see in the dark theme. Screenshot is attached.
![screenshot_2016-08-18-12-35-22](https://cloud.githubusercontent.com/assets/2184268/17782283/c1da6372-6540-11e6-8b43-0abf5301388b.png)

**Comment by mvysny** [comment] 2016-08-19 08:18
Hmm, works for me on my phone (Android 5.1 though). Please let me try to reproduce this issue on the Android 4.0.4 Emulator.

**Comment by mvysny** [comment] 2016-08-23 21:21
Failed to reproduce on the SDK 10 emulator:
![screenshot from 2016-08-23 23-20-34](https://cloud.githubusercontent.com/assets/254091/17910230/4589daa4-6988-11e6-8d72-74b8fa3a52a1.png)

**Comment by mvysny** [comment] 2016-11-24 12:31
I apologize, but it is next to impossible tofix this. This seems to be a theming issue on Android 4.0.4 on your phone. The only way to fix this is to randomly try random solutions like this one: http://stackoverflow.com/questions/26843098/android-appcompat-v721-0-0-change-material-checkbox-colors
But I can't really test whether the solution actually works.
Hmm. How about the checkboxes in the Launch Quiz screen? Are those visible? Can you please give me a screenshot of a screen where the checkbox is visible for you properly?

**Comment by mvysny** [comment] 2016-11-24 12:36
Edit: ah great. Fucking Android. I can't simply do new CheckBox() otherwise it is black. I have to inflate a CheckBox from a layout, for the CheckBox to have a proper background.

**Comment by mvysny** [comment] 2016-11-24 12:51
Fixed in Aedict 3.39.27

**Closed by mvysny** 2016-11-24 12:51 UTC
Labels: android workaround, bug
