### ISSUE TITLE
"Examples" tab shows incorrect sentences for some words

### ISSUE THREAD

**Issue by renattou** [mvysny/aedict#674] opened 2016-05-19 11:39 UTC
2 months ago I mentioned it in a review, but I forgot to open the issue at that time.

There are some sentences that show up as examples, because the word is detected when it shouldn't. I don't know how to explain it very well, so I'll give some examples.
- For 止める（やめる）, there are some examples with 止める（とめる） and even とめる without kanji.
- For ので・んで, it shows some examples like 住んでいる and 二人で（ににんで）, probably because they contain んで. A lot of the examples for this one are incorrect.
- For 彼 (vocabulary, not kanji), it shows examples 彼女.
- For 家 (vocabulary, not kanji), it shows examples with 画家 and 家族.

There are also cases that I'm not sure whether they are correct or not, because the sentence shows a word that has the searched word as part of it with the same reading.
- For 同意, it also shows examples for 同意見 or 同意語.
- For 彼 (vocabulary, not kanji), it shows examples for 彼ら.

I found many more cases that this happened, but I don't remember many of them. I just searched these now from my notepad, but I think they already give a general idea of the problem.

**Comment by mvysny** [comment] 2016-05-25 17:29
Thanks for letting me know. Yet, I am not sure whether this is actually fixable. A lot of example sentences lacks separate word list, so there is no way for Aedict to know e.g. that in this particular sentence 止める reads as とめる. Therefore, currently Aedict simply searches by a substring. 

Yet, I have to agree that the example sentence matcher could definitely do a better job. Perhaps it should first find sentences with correct word analysis, matching given JMDict entry, then it can fallback to the old substring search.

**Comment by kcroker** [comment] 2016-06-18 11:48
Yeah, I've got the same trouble.  Searching for 実 like "seed" brings up a bunch of じつ and then strangely switches to showing me 子 (and highlighting that).

**Comment by mvysny** [comment] 2017-06-22 18:36
@kcroker hmm, I am not able to reproduce your issue. Searching for 実 examples brings the correct example sentences; also showing example sentences for the 実 entry will bring up correct answers. However, if you still can reproduce your issue, please open a new bug report and attach a screenshot.

**Comment by kcroker** [comment] 2017-09-05 03:36
I haven't run into it again.  I'm digging through my starred emails, and
found this one :D

Suggestion: when I copy text to the clipboard to be translated, it fires up
the dictionary on the first run.  This performs a dictionary update check,
which either faults out if I'm in airplane more or tells me to upgrade.
The bad thing is that these notifications appear directly on top of the
translation text, and I cannot make them go away (I just have to wait for
them to fade).  Could you please address this?

Thanks!
-k

**Comment by mvysny** [comment] 2017-09-05 07:12
@kcroker thanks for letting me know. I'll thus close this bug as fixed, please reopen if you bump into it again.

> Suggestion:

You can edit the dictionary check frequency in `Settings / Dictionary / Automatic Check for Updates` as a workaround; please fill in a new bug for this.

**Closed by mvysny** 2017-09-05 07:12 UTC
Labels: bug
