### ISSUE TITLE
Crashing constantly when trying to view examples

### ISSUE THREAD

**Issue by sblevine** [mvysny/aedict#618] opened 2016-02-17 19:10 UTC
Lookup demasu.  Select first entry.  Go to examples. Crashes.  Galaxy s6 edge runnung 5.0.2 andoid. Delete and reinstall no help.   Hasbeen occuring several words since recent update.

**Comment by mvysny** [comment] 2016-02-17 20:47
Thank you for letting me know, and I apologize for the crash. I have reproduced the issue, fixing now.

**Comment by sblevine** [comment] 2016-02-17 20:48
Thanks for prompt attention and fine app.

**Comment by mvysny** [comment] 2016-02-17 20:55
This is actually a duplicate of #616 - when selecting the Examples Tab, Android is trying to also create the contents of the Inflections tab, which will crash as my inflector code was not capable of inflecting ichidan verbs with kanjis. Fixed in Aedict 3.39.7, I will release the fixed version tomorrow.

**Closed by mvysny** 2016-02-17 20:55 UTC
Labels: bug
