### ISSUE TITLE
Issues with exported furigana (for Anki / AnkiDroid)

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#493] opened 2015-05-05 03:13 UTC
生き返る gives the following for furigana:
生き返る[いきかえる] 生返る[いきかえる] 生きかえる[いきかえる]

It should be:
生[い]き 返[かえ]る, 生[いき] 返[かえ]る, 生[い]きかえる

i.e. there are 3 issues: 
1) It's missing the comma separator which is included with the kanji results
2) Kana are incorrectly included inside the square brackets for words with mix of kanji and kana
3) In the case where there are multiple sets of brackets, there needs to be a space before each subsequent kanji so that the text in the brackets is centered in the correct place (above the kanji)

**Comment by timrae** [comment] 2015-05-07 16:24
Here's some code which I'll donate (under creative commons license) that seems to work:

```
    private static final Pattern KANA_REGEXP = Pattern.compile("[\u3041-\u309e\uff66-\uff9d\u30a1-\u30fe]+");
    private static final String RUBY = " %s[%s]";

    private String makeFurigana(String kanji, String reading) {
        Matcher kanaMatcher = KANA_REGEXP.matcher(kanji);
        // All characeters are kanji; simple replacement will work
        if (!kanaMatcher.find()) {
            return String.format(RUBY, kanji, reading);
        }
        // Strip off any kana from the beginning of the word
        StringBuilder output = new StringBuilder();
        if (kanaMatcher.start() == 0) {
            String prefix = kanaMatcher.group();
            kanji = kanji.substring(prefix.length());
            reading = reading.substring(prefix.length());
            output.append(prefix);
            kanaMatcher = KANA_REGEXP.matcher(kanji);
        } else {
            kanaMatcher.reset();
        }
        // Now step through each kanji
        int lastKanaEnd = 0;
        int lastReadingKanaEnd = 0;

        while (kanaMatcher.find()) {
            // Find the next kana in the kanji string
            int kanaStart = kanaMatcher.start();
            String currentKana = kanaMatcher.group();
            // Extract the kanji in-between the current kana and the previous kana
            String currentKanji = kanji.substring(lastKanaEnd, kanaStart);
            // Set the end index of current kana in kanji string for next loop iteration
            lastKanaEnd = kanaMatcher.end();
            // Find the current kana in the reading string
            int readingKanaStart = reading.indexOf(currentKana, lastReadingKanaEnd);
            // Extract the reading in-between the kana found in the kanji this time and last time
            String currentReading = reading.substring(lastReadingKanaEnd, readingKanaStart);
            // Set the end index of current kana in reading string for next loop iteration
            lastReadingKanaEnd = readingKanaStart + currentKana.length();
            // Append current kanji and reading to the StringBuilder as furigana
            output.append(String.format(RUBY, currentKanji, currentReading));
            // Append the current kana to the StringBuilder (outside the furigana)
            output.append(currentKana);
        }
        // Add any kanji / reading at the end of the string to the builder
        if (lastKanaEnd < kanji.length()) {
            String currentKanji = kanji.substring(lastKanaEnd+1);
            String currentReading = reading.substring(lastReadingKanaEnd + 1);
            output.append(String.format(RUBY, currentKanji, currentReading));
        }
        return output.toString().trim();
    }
```

**Comment by mvysny** [comment] 2015-05-08 08:02
Thanks for letting me know. I haven't touched the export code for quite a long time, can you please refresh my memory on what steps I need to take to reproduce this issue? Thanks ;)

**Comment by timrae** [comment] 2015-05-08 08:04
Search for 生き返る via the API, and check the furigana field

**Comment by timrae** [comment] 2015-05-08 08:08
By the way, it seems that the setting `Export > Export Ruby Furigana` is doing anything...? It seems to export furigana regardless of this setting

**Comment by mvysny** [comment] 2015-05-13 14:50
Regarding the Export Ruby Furigana: it does exactly as it says: in the CSV/AnkiDroid Flashcard export you can either export kanji only such as 生き返る, or ruby furigana such as 生き返る[いきかえる].
The API returns a map string->string for each entry, use map.get("%kanji%") to get pure kanjis, use map.get("%furigana%")

**Comment by mvysny** [comment] 2015-05-13 14:52
I will fix the ruby furigana to be exported as you wish, that is: 生[い]き 返[かえ]る

**Comment by mvysny** [comment] 2015-05-13 15:03
Actually, I will use a bit different format, illustrated by this example: an entry 勉強を怠ける will be represented by the following ruby furigana string {勉強;べんきょう}を{怠;なま}ける
Furiganas will be separated by a comma ,

**Comment by timrae** [comment] 2015-05-13 15:04
Then it won't work with Anki though... and I hope you didn't miss the part where I *gave you* the code to do this...?

**Comment by mvysny** [comment] 2015-05-13 15:10
I thought that Anki/AnkiDroid is a general purpose tool. Is there a reason why it supports exactly the format which you provided, that is, 生[い]き 返[かえ]る?
Okay, I will add another formatting string %furigana_anki% which will contain the output of your code.

**Comment by mvysny** [comment] 2015-05-13 15:17
Fixed in Aedict 3.19, please reopen if the solution is not satisfactory.

**Comment by timrae** [comment] 2015-05-13 15:17
I don't know the reason why Damien chose that format, but Anki has been using it for many years... I'm not sure why you suddenly want to change the Aedict format to something else...? Has someone requested a different format?

**Comment by mvysny** [comment] 2015-05-13 15:18
The FuriganaView uses the abovementioned {} format: https://github.com/sh0/furigana-view, for example {彼女;かのじょ}は{寒気;さむけ}を{防;ふせ}ぐために{厚;あつ}いコートを{着;き}ていた。
Thanks for explaining, there will now be the %furigana_anki% map key which will contain the furigana in the [] format.

**Comment by mvysny** [comment] 2015-05-13 15:25
Btw thanks for the code ;)

**Comment by timrae** [comment] 2015-05-13 15:26
I see... In AnkiDroid and probably Anki we just convert from that format I gave you to the standard HTML [ruby tag](http://www.w3schools.com/tags/tag_ruby.asp), and display that in a WebView. Does `Html.fromHtml()` not work for Ruby?

**Comment by mvysny** [comment] 2015-05-13 15:28
> Does Html.fromHtml() not work for Ruby?
I have no idea... I also tried the ruby tag myself but it did not worked half a year ago for me, so I'm surprised you guys are using it. Does it work?

**Comment by timrae** [comment] 2015-05-13 15:42
Yes, it works perfectly in a `WebView`. I just tried it in a `TextView` and it doesn't seem to work there though unfortunately... the <ruby> tags are simply stripped out

**Comment by mvysny** [comment] 2015-05-13 16:35
I believe that the ruby tag does not work in newest Firefox as well, and also in other browsers: http://caniuse.com/#search=ruby

**Comment by timrae** [comment] 2015-05-13 23:16
My interpretation of that page is that it does work in the latest version
of all browsers except opera mini

**Comment by timrae** [comment] 2015-05-13 23:25
I just confirmed that it's working in latest version of Chrome and Firefox for PC:

```
<html><ruby>寿司<rt>すし</rt></html>
```

**Comment by mvysny** [comment] 2015-05-14 07:39
You're right, I have just updated to firefox 38 and it's working well:
```<html><head><meta charset="UTF-8"></head><body><ruby>寿司<rt>すし</rt></ruby></body></html>```
A shame that in WebView it will not work on 50% of phones because of old webkit or for other reasons. Yes, I'm tired of Android.

**Comment by timrae** [comment] 2015-05-14 07:44
I'm not sure where you came up with that number... It works in WebView for
API 11 and above, which is 90% of all devices.

**Comment by mvysny** [comment] 2015-05-14 14:26
As I said, I am presently tired of Android and of its endless compatibility issues, and I am now very pessimistic that something really works for API 11 and above ;) Because I have found Android API methods which should work from API 1 but apparently do not work on some phones on Androids 4.1.2 etc.
But, we have strayed from the initial issue, please let us stop this discussion ;)

**Comment by mvysny** [comment] 2015-05-22 14:03
The code fails with:
java.lang.StringIndexOutOfBoundsException: length=25; regionStart=4; regionLength=-5
at java.lang.String.startEndAndLength(String.java:593)
at java.lang.String.substring(String.java:1474)
at sk.baka.aedict3.util.FuriganaUtil.makeFurigana(FuriganaUtil.java:82)
@timrae can you please take a look at the code? Unfortunately I do not have the input strings...

**Comment by timrae** [comment] 2015-05-23 01:04
Do you mean it fails all the time? Or it failed once with a particular input? I only tested it with Java 7

**Comment by mvysny** [comment] 2015-05-23 20:50
It only fails for some particular input combination. I have tried it and it worked,  but now I have found this error report in my android console... It does not occur frequently so I guess it only fails for some words.

**Comment by timrae** [comment] 2015-05-23 23:51
The algorithm assumes that the word is made up of kanji and kana only.
Maybe there are some entries that have romaji or other characters?

**Comment by mvysny** [comment] 2015-05-25 17:13
Okay, should be fixed now, let's see if the fix helps.

**Closed by mvysny** 2015-05-25 17:13 UTC
Labels: enhancement, user feedback needed

**Comment by timrae** [comment] 2015-06-19 16:42
I have updated the code to fix a bug:
https://gist.github.com/timrae/e9efadbfe59a8473389b
