### ISSUE TITLE
Unable to erase an item in a notepad

### ISSUE THREAD

**Issue by otax38** [mvysny/aedict#793] opened 2017-08-29 20:12 UTC
Hi Martin,

For memory, the bug we discussed already : 

I made recently a mistake in my Notepads.
So I tried to transfer an item  from one Notepad to another with the "Move to Category" option.
It went well in the destination, but not at the original Notepad in the sens that it remains.
As a result, my word is now in 2 Notepads.
So I tried the "Delete selected" in the same options menu, but it did nothing, and remains.

Settings 
In user data, my choice was : Notepad : Add Unique Only, so it is strange It could duplicate when moving.
In expert settings, I think i am quite regular (no use of SD Card Storage, only internal memory) File-based option.

Thanks,
Regards,
JPierre.

**Comment by mvysny** [comment] 2017-09-12 08:28
Hi, thanks for the report and I apologise for the issue. Unfortunately I can't reproduce this issue on my phone - the deletion of selected entries works correctly for me. Can you please create a category and add such entries there so that the bug is easily reproducible? Thanks!

**Comment by otax38** [comment] 2017-09-12 16:49
Hi, thanks for trying to solve that.
I am not sure to understand what I can do for helping  ...

1) create a new empty category  (OK, understood)
2) I add only items that are already in my other categories (Notepads)  ?
3) I do that for plenty items and check if some can be erased or not ?

NB : I tried to create a bug report, but my phone doesnt work correctly with Android Device Monitor (device not seen) :-(

**Comment by mvysny** [comment] 2017-09-12 16:53
Basically, since I can't reproduce the issue, you will have to find a smallest set of steps which reproduces the issue. I will then try to repeat those steps and reproduce the issue - if I successfully reproduce the issue only then I can fix it. So I was thinking that you should start with an empty category, add couple of items and try to delete them. If the items are not deleted, awesome - we have a reproducible set of steps. If the items are deleted, then please try further ;)

> NB : I tried to create a bug report, but my phone doesnt work correctly with Android Device Monitor (device not seen) :-(

Yeah, you'll need to enable the developer mode on your phone. Please see e.g. https://www.greenbot.com/article/2457986/android/how-to-enable-developer-options-on-your-android-phone-or-tablet.html for more details

**Comment by otax38** [comment] 2017-09-12 17:13
OK, understood, thanks.

NB: developer mode was activated (I tried under Windows and Linux, but both couldnt see my phone)
Problem must be between chair and keyboard ^^

**Comment by otax38** [comment] 2017-09-12 18:41
For the moment, all my attempts cannot reproduce the bug also ! (create, move, erase, all OK)
I must find the items that I couldn't erase and try again.
The problem is to find them (I didn't pay attention to them exactly!!), I have around 800 items in about 30 notepads.
Is there a way to find double entries in notepads ?

**Comment by mvysny** [comment] 2017-09-12 18:54
> Is there a way to find double entries in notepads ?

Sorry, not at the moment.

**Comment by otax38** [comment] 2017-09-29 18:05
Hi Martin,

I am back with new info.
I imagine this is linked with previous problem.

I created a new category.
I put 5 items in it.
Then I try to delete the last one in the list (alphabetic order)
But the last is not deleted, it is the previous one in the list that is deleted.
Then I repeat the operation, and again, the previous one is deleted.
After 4 delete operations, only the one that I wanted to delete remains.
Finally that item is deleted correctly because it is the last one in the category.

Can you reproduce that ?

Best regards.

**Comment by mvysny** [comment] 2017-10-02 07:06
Hi, I tried steps as provided by you, and for me it works properly - the last entry is properly deleted. Perhaps this bug can only be reproduced for some particular entries only? Can you please list the entries here, or share a screenshot from your phone? Also, which version of aedict are you using?

**Comment by otax38** [comment] 2017-10-02 17:41
Hi Martin,

Thanks for your trial.
Here is a snap :
[https://photos.app.goo.gl/37J0BTq3oJtgidv52](url)

I was using previous version of 3.44.
Under 3.44 result is the same

Regards.

**Comment by otax38** [comment] 2017-10-02 17:45
Oops, sorry, I didn't manage to insert my link properly, but the URL is OK.

https://photos.app.goo.gl/37J0BTq3oJtgidv52

**Comment by mvysny** [comment] 2017-10-03 09:09
Thanks! To reproduce, the following entries must be present in a category:

1. 清潔 せいけつ
2. 整理 せꜜいり
3. 清掃 せいそう
4. 整頓 せいとん
5. 躾 しつけ

Let me try those out for myself.

**Comment by mvysny** [comment] 2017-10-03 09:15
Actually I have failed to reproduce the issue - when I tried to delete the last one shitsuke (by long-touching it, making sure that only one entry is selected and then I pressed "Delete"), it got properly deleted:
 
![device-2017-10-03-121335](https://user-images.githubusercontent.com/254091/31117919-50fc2ef0-a834-11e7-93ca-316cbea1c9fd.png)

Aha! But let me try to change the "Sort" setting to "By first common reading romanized in Kunrei Shiki".

**Comment by mvysny** [comment] 2017-10-03 09:16
Reproduced! It is important to change the "Sort" setting from "As they were added" to "By first common reading romanized in Kunrei Shiki", then the bug is easily reproducible on nearly any notepad.

**Comment by mvysny** [comment] 2017-10-03 11:13
Fixed in Aedict 3.45

**Closed by mvysny** 2017-10-03 11:13 UTC
Labels: bug

**Comment by otax38** [comment] 2017-10-03 11:22
Hi Martin,

You got it !

Thanks a lot.
With best regards,
Jean-Pierre.
