### ISSUE TITLE
Notepad Category (inner structure)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#370] opened 2015-03-14 07:02 UTC
```
I know, I want it all, but could you include a way to sort the contents of a 
category too?

Example:

I am playing GAME A and need to make additional "sub-categories", so I have all 
verbs of a category under a big lettered/colored title inside a category. So, 
inside a category there is some structure too (now words are just thrown in by 
date added).

Or as I suggested before, when pressing "notepad", you reach a place where all 
categories are listed at once. Then when entering a category visually evrything 
is like when entering "notepad" generally (horizontal slide menue). 

So instead of general categories, like we have now, the whole notepad interface 
would be realized specifically for GAME A, the whole horizontal menue would be 
used to display the "verbs", the "adjecrives", "nouns", "expressions" etc. of 
GAME A.  

At class I summarize sessions, pages of our study book, adding words to a 
category which would be named "lesson 15", "lesson 16", etc. 
So I need some "inside"-structure here too instead of just randomly thrown in 
kanji.

Please give notepad some structure (:
```

Original issue reported on code.google.com by `dezorian...@gmail.com` on 29 Nov 2014 at 9:26

**Comment by mvysny** [comment] 2015-06-15 08:07
The list of categories should somehow be searchable, if the user has TONS of categories.

**Comment by mvysny** [comment] 2017-06-23 08:05
Duplicate of #696 which also request two-level notepad category system.

**Closed by mvysny** 2017-06-23 08:05 UTC
