### ISSUE TITLE
Sentence analysis hangs

### ISSUE THREAD

**Issue by tselnekovic** [mvysny/aedict#761] opened 2017-05-20 16:44 UTC
Sentence analysis doesn't work correctly. After I copy a japanese sentence into Aedict (from Wikipedia, for example), the sentence analyzer just hangs and won't show the sentence analysis results with the Kanjis displayed. This is easily reproducible in the aedict-online.eu as well as in the Android version of the application. I have tried shorter and longer sentence, always the same result. Occasionally, the results are displayed, but in 90% the cases the sentence analysis just hangs on searching.

**Comment by mvysny** [comment] 2017-05-21 16:26
Hi, I am sorry to hear that. Can you paste such sentence here, so that I can try it on my phone?
Also this may happen if you have too many dictionaries enabled in settings / dictionary / custom dictionaries. Can you please try to select only the jmdict there, then retry the analysis and check that it helped?

**Comment by mvysny** [comment] 2017-06-22 18:40
Closing since there's been no reply and I can't reproduce the issue. Please reopen if you're still experiencing this bug, and add more details.

**Closed by mvysny** 2017-06-22 18:40 UTC
Labels: bug, user feedback needed
