### ISSUE TITLE
Unexpected search results for "buta"

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#491] opened 2015-05-04 14:08 UTC
In Aedict 3.17, I searched for "buta" in JMDict with "JP match" and "Sense" both set to "Exact". I got 豚 (pig) as expected, but also, many other results that don't appear to have buta/ぶた/ブタ in them. See 2 attached screenshots.
![screenshot_2015-05-04-10-03-44](https://cloud.githubusercontent.com/assets/2184268/7454796/1dcf9dc0-f245-11e4-80ad-bb0811a2dad9.png)
![screenshot_2015-05-04-09-52-59](https://cloud.githubusercontent.com/assets/2184268/7454804/32bef44c-f245-11e4-81c7-f0c276334362.png)

**Comment by mvysny** [comment] 2015-05-04 14:14
Hi, this is because e.g. 深い also translates to Hungarian "alapos, mély, mélyen, mélység, óceán, ravasz, bizalmas, buta, közeli, legvastagabb része vminek, nehéz felfogású, sűrű, sűrűn, vastag, befejezés, hű, közel, pontos, sikátor, szoros, szűkmarkú, tartózkodó, zárt, zsugori" which contains buta. This is a duplicate of https://github.com/mvysny/aedict/issues/471
Please make sure that you have Aedict 3.16 or newer installed, then head to Settings / Dictionaries / Dictionary Manager and update all dictionaries. I have just today released a new bunch of dictionaries which should now return only relevant results.
Closing as fixed, please verify that the problem is fixed and let me know if not.

**Closed by mvysny** 2015-05-04 14:14 UTC
