### ISSUE TITLE
Add an option to remove the results from the kanjipad screen

### ISSUE THREAD

**Issue by blastrock** [mvysny/aedict#530] opened 2015-06-24 20:09 UTC
Hi,

Just above the pad part of the kanjipad screen, there are buttons, and I can't see all of them on my phone. More importantly, the last button (which resets the pad) does not appear at all when I hold my phone vertically. I have the same problem (though I see more of the buttons) with a small tablet I have.

I saw that, on smaller screens, the kanjipad would take a greater part of the screen, and the result are shown at the top of the screen. I think the same layout should be kept for screens a little bigger than that. And the best thing would be to add an option in the settings to force one layout or the other as people prefer.

That would also help me draw the kanjis since it's easier to have aedict recognize the kanjis if I can draw it better on a bigger pad.

Other than that, aedict is a nice soft, keep up the good work :)

**Comment by mvysny** [comment] 2015-07-01 05:55
Hi, thanks for letting me know. Can you please post the exact sizes (both inch and pixels) of both of your phone and your tablet? I will then run Aedict in the emulator and I will fix this. Thanks!

**Comment by blastrock** [comment] 2015-07-01 17:02
My phone is a nexus 5 with a 1920x1080 screen on which I changed the DPI setting to 360 dpi, which means the virtual size of the screen 6.12 inches. The real size (though I don't think it matters here) is 4.95 inches.

The tablet is a lenovo a3000 which does not have any fancy setting, it has a resolution of 600x1024 and a size of 7 inches.

**Comment by mvysny** [comment] 2015-07-02 08:28
You're right, on 7" tablet in portrait mode the button is chopped and there is little room for the kanjipad:
![device-2015-07-02-102708](https://cloud.githubusercontent.com/assets/254091/8472855/f1a58082-20a4-11e5-9e42-8d08a06b32a9.png)

**Comment by mvysny** [comment] 2015-07-02 08:48
Fixed; 7" tablet in portrait mode will use the same layout as a small phone does. The two-column-with-search-results mode will only be used on 7" tablets when they are in the landscape mode.
Cannot verify the fix on Nexus5 though as changing the DPI AFAIK requires rooting of the phone. Marking as fixed, please let me know if the problem is fixed also on your Nexus 5 phone.
Fixed in Aedict 3.27

**Closed by mvysny** 2015-07-02 08:48 UTC
Labels: bug

**Comment by blastrock** [comment] 2015-07-02 20:54
Yes it is, thank you!
