### ISSUE TITLE
Reader:Crash on clipboard copy

### ISSUE THREAD

**Issue by dpasca** [mvysny/aedict#664] opened 2016-04-21 05:28 UTC
Upon clipboard copy, the popup stays up with a spinning wheel while a termination dialog comes up.
I’ve sent a couple of automatic reports.
This is on a Note 5 with 5.1.1 . First time user.
Thanks.

**Comment by mvysny** [comment] 2016-04-21 07:37
Thank you for the bug report, and I apologize for the crash. I can see the crash in my Google Play console, I'll look at it and I'll let you know.

**Comment by mvysny** [comment] 2016-04-21 07:47
Hmm, this is weird. Reader asks Aedict to translate stuff, and for some reason, Aedict thinks you have no dictionaries installed locally. Can you please try opening Aedict and performing a couple of searches? Also, Please head to Aedict Settings, Dictionaries, Dictionary Manager, and in the upper-right menu, Dictionary Health Check, to see if there are any reddish text? Thanks!

**Comment by dpasca** [comment] 2016-04-21 08:36
Hi Martin,

Cool ! Mystery solved !
I did buy Aedict3 for the popup service and installed on request, without
actually opening it not even once, so the dictionaries weren’t downloaded.

I guess for a first time users that come straight for the popup, it would
make sense to put an warning dialog suggesting to download the dictionaries.

Anyhow, everything works now, Thanks !

**Comment by mvysny** [comment] 2016-04-21 09:59
I *knew* there is something weird going on :-D Thank you for letting me know. I will make the Reader Popup show a correct error message instead, perhaps even automatically open Aedict.

**Comment by mvysny** [comment] 2016-04-21 10:22
Pasting technical crash stack trace from Google Play:

java.lang.RuntimeException: java.lang.IllegalStateException: No JMDicts locally present???
	at sk.baka.aedict3.search.SearchService$IncomingHandler$1.onFailure(SearchService.java:79)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.onFailure(LoaderEx.java:181)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.access$100(LoaderEx.java:105)
	at sk.baka.aedict3.util.android.LoaderEx$Loader$1.run(LoaderEx.java:158)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6897)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.IllegalStateException: No JMDicts locally present???
	at sk.baka.aedict.search.impl.MultiJMDictSearch$Companion.newSearch(MultiJMDictSearch.kt:65)
	at sk.baka.aedict.search.impl.MultiJMDictSearch.newSearch(MultiJMDictSearch.kt)
	at sk.baka.aedict.search.JMDictQuery.search(JMDictQuery.java:69)
	at sk.baka.aedict3.search.GlobalSearchHandler$QueryLoader.loadItemsInBackground(GlobalSearchHandler.java:133)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.run(LoaderEx.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by mvysny** [comment] 2016-04-21 14:01
Fixed in Aedict 3.39.17: if Aedict dictionaries is missing, a single result is provided: "Aedict dictionaries are missing, please start the Aedict application to download them"

**Closed by mvysny** 2016-04-21 14:01 UTC
Labels: bug
