### ISSUE TITLE
Writing on external SD-Card is failing

### ISSUE THREAD

**Issue by malek78i** [mvysny/aedict#875] opened 2019-04-10 13:58 UTC
Phone Model: LG K4 2017
Android Version: 6.0.1
Screenshot of this issue: <a href="http://de.tinypic.com?ref=vi2r13" target="_blank"><img src="http://i65.tinypic.com/vi2r13.png" border="0" alt="Image and video hosting by TinyPic"></a>

Description: When I choose my external SD-Card to download the files, it says that the SD-Card is probably set to read-only or is not properly installed. But it works fine.
Any solutions?

**Comment by mvysny** [comment] 2019-04-10 14:09
Since shitty Android doesn't provide any insight as to why the SD-Card write fails, we can only guess. Perhaps Aedict doesn't have a permission to write to the SD-Card - please make sure that there is necessary permission. Aedict should have asked for that though. Also, please try different path on your SD-Card, e.g. `/storage/C6AF/1903/aedict3`. Also, make sure that the path to the SDCard has been detected properly - e.g. you can try `/sdcard` or other.

**Comment by malek78i** [comment] 2019-04-10 14:22
I can't use my internal sd card because its full. Unfortunately, I cannot try a different path too ore name it. Its disabled

**Comment by malek78i** [comment] 2019-04-10 14:37
Is there a way to add permission for external sd card writing in the app's code?

**Comment by mvysny** [comment] 2019-04-10 15:21
The app already requests those in `AndroidManifest.xml`:
```xml
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

You can go to your Android's Settings, Apps & Notifications, then find Aedict, Permissions and make sure that the "Storage" permission is enabled.

**Comment by malek78i** [comment] 2019-04-10 16:29
"Storage" permission enabled, still no success

**Comment by malek78i** [comment] 2019-04-17 15:51
Is there anything new related to this issue? Because its quiet here😁

**Comment by mvysny** [comment] 2019-04-17 16:41
Unfortunately, because I don't own a device same as yours, I can't reproduce the issue. We can't learn the true nature of why the directory failed to be created - Android API is horrible and all it returns is `false`.
Android 6 introduced the concept of permissions - Aedict should ask for a permission to write to the SD Card. Did this happen? Did Aedict asked for permission to access SD Card and did you give the permission?

**Comment by malek78i** [comment] 2019-04-17 19:57
It only asked for "Storage"-Permission which I allowed that. More permission it did not ask.

**Comment by mvysny** [comment] 2019-04-18 16:38
That should be enough. Sometimes when upgrading to a newer Aedict which takes advantage of the new permission system, the SD Card write permission is not granted by the Android OS even though you confirmed it in the dialog. Could you please try to reinstall Aedict?

Alternative is to upgrade to Android OS 8.0 or higher - a new API is present there, which will properly state the cause as to why it can't write to the SD Card.

**Comment by malek78i** [comment] 2019-04-18 16:42
I reinstall it. Still no success :/
But, no problem! Thank you for trying to solve this issue!

I can't upgrade to a newer Android Version. It is not released (yet?) from my manufacturer.

**Comment by mvysny** [comment] 2019-04-18 16:48
I'm sorry that I failed to fix it. It's very hard to fix such issues with Android fragmentation.

> I can't upgrade to a newer Android Version. It is not released (yet?) from my manufacturer.
Unfortunately, it probably never will be. Android 8/9 requires some changes to the filesystem and it's hard to upgrade to; also the vendor wants you to buy a new phone instead of using the old one. That's why vendors generally don't upgrade older phones. You can try to buy a new phone which supports Android One (I did); alternatively OnePlus has quite good record of keeping OS up to date.

**Comment by mvysny** [comment] 2019-04-18 16:52
I'm sorry but I am closing this bug as won't fix; I've pushed new Aedict 3.50.14 with support for better error reporting (even though that's only for Android 8.0+).

**Closed by mvysny** 2019-04-18 16:52 UTC
Labels: android workaround, cannot reproduce, question

**Comment by malek78i** [comment] 2019-04-19 18:54
I have a little question about Aedict Ultimate. I can't purchase it

**Comment by mvysny** [comment] 2019-04-20 03:17
> I have a little question about Aedict Ultimate. I can't purchase it

I'm sorry to hear that. Please open a new bug report with more information on the matter - what you tried and what failed for you. Thanks!

**Comment by mvysny** [comment] 2019-04-20 19:22
There is a workaround, please see #876 for more information.
