### ISSUE TITLE
*minor issue* Furigana overlaps at times

### ISSUE THREAD

**Issue by ghost** [mvysny/aedict#704] opened 2016-11-15 02:27 UTC
Furigana overlaps at times as shown in the first example sentence for the kanji 頂:
    十分頂きました。

Issue found on Samsung Galaxy S5

**Comment by mvysny** [comment] 2016-11-15 05:39
Reproduced on my phone, thank you for letting me know.

**Comment by mvysny** [comment] 2017-06-26 18:02
This is actually a bug in Furigana View: https://github.com/sh0/furigana-view - would somebody be interested in reporting and/or fixing the bug?

**Comment by rbleuse** [comment] 2020-08-07 09:22
Does this commit fix the issue ?

https://github.com/blayzew/furigana-view/commit/72848b29d6e589ead3d0c3e9f8f2fa54d8e6011f

**Comment by mvysny** [comment] 2020-08-11 05:23
Good find, thank you! Unfortunately that commit only fixes minor things like rendering the entire content out of the viewport, or preventing IndexOutOfBoundException from being thrown in certain cases. Actually, both fixes are already present in Aedict.

**Comment by rbleuse** [comment] 2020-08-11 15:14
If you can change the furigana lib, you can try with this one : https://github.com/guentoan/FuriganaView

I checked and it seems to be working

<img src="https://user-images.githubusercontent.com/626863/89914982-13de6080-dbf6-11ea-80a6-3e6ba484ee4b.png" widh="300" />

**Comment by mvysny** [comment] 2020-08-14 07:22
Awesome find, thank you :+1: Let me try to integrate the view into Aedict.

**Comment by mvysny** [comment] 2020-08-14 07:51
Yup, works better than the old Furigana View. Fixed in Aedict 3.50.18.

**Closed by mvysny** 2020-08-14 07:51 UTC
Labels: bug
