### ISSUE TITLE
Add to notepad should list in descending chronological order

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#548] opened 2015-08-22 14:37 UTC
If one has many notepads, chances are that newer notepads (ones that are being constructed for new vocab sets) are being accessed most frequently.  It wastes time to scroll down to the bottom of the notepad list to add to one's most recent notepad.  Same thing for requesting quizzes: the list should be in descending chronological order.

**Comment by mvysny** [comment] 2015-08-25 05:05
Thanks for reporting the issue. If I understand correctly, the problem is as follows:
1. you long-click on an item and select the "Add to Notepad" button. The "Select category" dialog lists the "Create new ..." option as the last one (it should be the first option).
2. After the notepad category is created, it should be added to the beginning of the category list, not appended at the end of the list.
3. To remedy the current state (most recent categories are at the end of the list), I will introduce an option which reverts the notepad category order, which should bring most recent categories to the beginning of the list.
Please let me know if this will help your situation.

**Comment by kcroker** [comment] 2015-08-25 14:32
Yes, such an option to reverse the listed order of categories would be
perfect.

However, "Create New" should probably still be at the bottom because one
does not often create new categories.

For example, at school I create a category each time we start a new
chapter, so every 14 days.  But, when I add the vocabulary to the newly
created category, I do 50 additions very rapidly during a 2 hour period.

**Comment by mvysny** [comment] 2015-08-27 19:42
Fixed in Aedict 3.32.

**Closed by mvysny** 2015-08-27 19:42 UTC
Labels: enhancement
