### ISSUE TITLE
Problem with aedict pop-up

### ISSUE THREAD

**Issue by corradoa2112** [mvysny/aedict#843] opened 2018-08-31 08:12 UTC
I read manga from the ebi Reader app and can not select any word so I have to open aedict pop-up from the drop-down menu on the screen and write the Japanese sentence. Now to open the app you need to copy a word from the aedict dictionary or from a Japanese site. Samsung A5 phone model code Sm-a520f Android software version 8.0.0

**Comment by mvysny** [comment] 2018-09-01 06:39
Thanks for the video, I can see now what the problem is. So the problem is that clicking the reader's notification icon doesn't show the reader popup itself. I don't have Android 8.0.0, but I'll try to reproduce this in the emulator.

**Comment by mvysny** [comment] 2018-09-01 08:35
The problem is that Android 8.0+ prevents firing broadcast messages, even from Notification's `PendingIntent.getBroadcast()`. The fix which works for me in the emulator is to instead use `PendingIntent.getService()` which invokes `Service.onStartCommand()`. Fixed in Aedict Reader 1.4.2

**Closed by mvysny** 2018-09-01 08:35 UTC
Labels: bug

**Comment by mvysny** [comment] 2018-09-01 08:42
Fixed in Aedict Reader 1.4.2 - please upgrade and let me know if the issue has been fixed.
