### ISSUE TITLE
Sentence analysis fallback

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#526] opened 2015-06-17 16:01 UTC
What's going on here? How did it turn 知って into 知行? It appears to have figured out the conjugation correctly (i.e. the bottom "fallback" is correct), but instead gives an apparently unrelated word which has more kanji than it started with... Which crashes my app.

![screenshot 18-06-2015 12-54-08 am 1](https://cloud.githubusercontent.com/assets/2818274/8212130/ea22c492-1554-11e5-8138-d6fc95c515a5.png)

**Comment by mvysny** [comment] 2015-06-18 07:16
Duplicate of #520

**Closed by mvysny** 2015-06-18 07:16 UTC

**Comment by timrae** [comment] 2015-06-18 07:28
My bad, thanks for the fix
