### ISSUE TITLE
No kanji entry for 〆る

### ISSUE THREAD

**Issue by pt-dev** [mvysny/aedict#873] opened 2019-04-06 16:25 UTC
しめる doesn't have a kanji tab when you look at the details. I think it's probably a weird kanji that might not even exist in the source dictionary data, but I thought I'd log it just in case.

**Comment by mvysny** [comment] 2019-04-16 18:49
Thanks! The source data are fine; the problem is that Aedict mistakenly doesn't consider 〆 to be kanji.

**Comment by mvysny** [comment] 2019-04-16 19:14
Actually you're right - the 〆 kanji is not present in the Kanjidic2. So even if I enable the Kanji tab, there is no data for such kanji. It's even questionable whether it indeed is a kanji: https://www.compart.com/en/unicode/U+3006 says it's Ideographic Closing Mark in CJK Symbols and Punctuation, so I wonder.
Maybe we should ask Jim Breen.

**Comment by pt-dev** [comment] 2019-04-17 00:04
The only reason I even found it was because my teacher explained that people used crossed fingers to get the restaurant cheque back in the day, and that the crossed fingers came from the Kanji for the verb.

**Comment by mvysny** [comment] 2019-04-17 17:22
Thanks for the story! :) I've modified Aedict to show the kanji and mention that there is no information on the kanji itself. Fixed in Aedict 3.50.14

**Closed by mvysny** 2019-04-17 17:22 UTC
Labels: bug
