### ISSUE TITLE
Portrait mode UI bug

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#890] opened 2019-09-25 02:08 UTC
Hi,

when I switch my phone to portrait mode, the search results doesn't fit the phone width

![Screenshot_20190912-082639](https://user-images.githubusercontent.com/626863/65563448-9a5d6580-df84-11e9-91b3-6f2f6fcc3f54.png)
![Screenshot_20190912-082458](https://user-images.githubusercontent.com/626863/65563450-9cbfbf80-df84-11e9-9e61-be4ad23b9d06.png)

Pixel 2
Android 10
Aedict 3.50.15

**Comment by mvysny** [comment] 2019-09-25 10:19
Hmm I can't reproduce it on my Android 9. Could it be an Android 10 quirk / incompatible change? Let me try in the Emulator. Does this happen all the time for you, or does the bug happen randomly?

**Comment by Spanja** [comment] 2019-09-25 10:53
I just tried, and I would say that it happens all the time, but only when I have a search.
It doesn't happen when recently viewed is displayed

**Comment by rbleuse** [comment] 2020-08-13 09:49
I can reproduce it on my Pixel 3A virtual device :

![image](https://user-images.githubusercontent.com/626863/90120446-0a223d80-dd5b-11ea-9e5a-1778ea34749b.png)

**Comment by mvysny** [comment] 2020-08-14 07:12
Ah, sorry, now I finally realized that it's not a bug - this is by design. If you touch any of the entry, it will actually show a quick preview of that entry in the right pane (in the blank spot).

If you would like to disable this functionality and make the search result list as wide as the screen, please go to `Settings / GUI Tuning / Other / Show entry previews` and uncheck that setting.

Please let me know whether this fixed the issue.

**Comment by rbleuse** [comment] 2020-08-14 07:27
Ah yes indeed, I didn't know about that. Thank you for the explanation !

**Comment by mvysny** [comment] 2020-08-14 07:34
No problem :+1: Closing as answered.

**Closed by mvysny** 2020-08-14 07:34 UTC
Labels: bug, user feedback needed
