### ISSUE TITLE
Multiple languages in definitions

### ISSUE THREAD

**Issue by Martin-interhand** [mvysny/aedict#801] opened 2017-09-25 13:44 UTC
Hello,
Aedict is very good for me, I use it a lot.  Thank you for your hard work!  Recently it started coming up with translations in quite a few European languages, as well as English.  The other languages are not of use to me, and it's a little distracting as I look to make sure I'm getting the whole definition or multiple definitions, to find myself trying to read the French, Spanish, or German.  Is there a way to go back to only English definitions?  I couldn't find anything in the settings menu that looked like it would do the job.
Thanks again for the software, it's very helpful!

**Comment by mvysny** [comment] 2017-09-25 14:05
Hi sure, please make sure that you have newest Aedict 3.43 installed, it should be fixed there. Closing as duplicate of #795

**Closed by mvysny** 2017-09-25 14:05 UTC
