### ISSUE TITLE
Unwanted Languages Now Appearing In Dictionary Entries

### ISSUE THREAD

**Issue by Higsby7** [mvysny/aedict#797] opened 2017-09-21 02:46 UTC
After updating about a week ago I am now seeing languages other than English listed on each dictionary entry's page. I have looked tireously through the settings and haven't found a way to get rid of them. Prior to updatng it was only showing English just like I want it to. Any help in getting rid of languages other than English would be greatly appreciated.

Thank you!

**Comment by mvysny** [comment] 2017-09-21 05:29
Thanks and I apologize. Unfortunately your settings are correct - it's the JMdict that has changed a bit and caused Aedict to show all translations. The issue is already fixed, I will hopefully push an update today later on.
Closing as duplicate of #795

**Closed by mvysny** 2017-09-21 05:29 UTC
