### ISSUE TITLE
Export Notepad as CSV (send to apps) won't work

### ISSUE THREAD

**Issue by andzzzzz** [mvysny/aedict#940] opened 2020-11-18 09:15 UTC
1. Your phone brand and maker
Sony Xperia 1 II

2. The exact Android version.
V10
Kernel-Version
4.19.81-perf+

When I try to export notepad as CSV and choose send to apps I immediately get a NullPointerException and nothing else. 
Already had a fresh install and it didn't help.

![Screenshot_20201118-100321](https://user-images.githubusercontent.com/74650667/99510049-dfadd500-2986-11eb-8750-2d74f1740be1.png)

**Comment by mvysny** [comment] 2021-01-26 07:56
Thank you for letting me know! This is a duplicate of #945 which has been fixed ;)

**Closed as completed by mvysny** 2021-01-26 07:56 UTC
Labels: bug, duplicate
