### ISSUE TITLE
`Words` pane for kanji doesn't correctly filter by prefix/suffix reading

### ISSUE THREAD

**Issue by mcallisterjp** [mvysny/aedict#900] opened 2019-12-02 22:32 UTC
When looking at the `words` for a kanji entry which has prefix/suffix kunyomi, filtering by that reading doesn't return the words using it (presumably because it's searching for the kunyomi followed by/following the hyphen indicating the prefix).

For example, the readings of 雨 are given as ウ、あめ、あま-、-さめ, but nothing shows up in `words` filtered by `reading: kunyomi あま-`, even though the readings of (for example) 雨戸 and 雨具 should match.

Found on OnePlus 3, Android v9, Aedict v3.50.16.

Screenshot: 
![Screenshot_20191202-221844](https://user-images.githubusercontent.com/4058060/70000874-c92f2380-1553-11ea-9afc-054e5bf1c8c7.jpg)

**Comment by mvysny** [comment] 2019-12-11 12:08
Thank you, reproduced, I'll take a look :+1:

**Comment by mcallisterjp** [comment] 2019-12-13 14:22
Thanks!

By the way, I went to go and fix this myself, but couldn't find the new codebase. Is that deliberate (perhaps related to the subscription model)?

**Comment by mvysny** [comment] 2019-12-14 12:44
Unfortunately it is deliberate. The sources present here are of the old Aedict 2. I'm not ready to open-source Aedict 3 just yet, because of piracy and the subscription model (especially the in-app purchase part of the app contains sensitive keys). Yet I myself value what OSS stands for; that's why not having Aedict 3 OSS troubles me. Yet, the working model of having OSS and selling services doesn't work for Aedict, so I'm keeping Aedict closed-source until I figure out a viable commercial solution (or resign, stop developing Aedict and donate Aedict to the community).

**Comment by mvysny** [comment] 2019-12-14 12:53
Thank you for reporting the issue, fixed :+1: 

Fixed in Aedict 3.50.17

**Closed by mvysny** 2019-12-14 12:53 UTC
Labels: bug

**Comment by mcallisterjp** [comment] 2019-12-14 15:00
Yes, I understand. Thanks for your hard work on this app! :+1:
