### ISSUE TITLE
Searching for Φ shows no results

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#716] opened 2016-12-07 08:16 UTC
Searching for Φ in AEdict results in no entries being returned even though searching for the other entries does return the entry (ie φ for example)

Here is the Jim Breen Japanese English dictionary entry that AEdict cannot find when searched for Φ:

<entry>
    <ent_seq>2173820</ent_seq>
    <k_ele>
        <keb>Φ</keb>
    </k_ele>
    <k_ele>
        <keb>φ</keb>
    </k_ele>
    <k_ele>
        <keb>ϕ</keb>
    </k_ele>
    <r_ele>
        <reb>ファイ</reb>
    </r_ele>
    <r_ele>
        <reb>フィー</reb>
    </r_ele>
    <sense>
        <pos>&n;</pos>
        <gloss>phi</gloss>
    </sense>
    <sense>
        <pos>&pref;</pos>
        <pos>&suf;</pos>
        <s_inf>confusion with ⌀ (ø), properly prefix read まる, also pronounced パイ</s_inf>
        <gloss>diameter (units assumed, esp. mm)</gloss>
    </sense>
</entry>

**Comment by mvysny** [comment] 2016-12-08 05:34
Thank you for letting me know. Reproduced, I'll fix this.

**Comment by mvysny** [comment] 2016-12-08 10:59
Fixed - the problem was not in Aedict itself, but in the dictionary index files. This issue will be fixed at 1.1.2017 when the next round of dictionary indexing/uploading takes place.

**Closed by mvysny** 2016-12-08 10:59 UTC
Labels: bug
