### ISSUE TITLE
[Feature request] Custom notes to an entry

### ISSUE THREAD

**Issue by ckaden** [mvysny/aedict#850] opened 2018-11-08 15:39 UTC
Hello,

I would be really happy about the possibility to add custom notes to vocabulary entries. Japanese is a language full of mysteries, exceptions, special cases and synonyms for different situations, so custom notes would be really handy.

Gui wise custom notes can be showed when being within an entry right on the first tab 'DICT', below everything else.
For convenience, all custom notes can be viewed either as an own tab within 'Notepad' or as an extra entry in the hamburger menu.

Thanks for your work!

(Happily subscribed today, I totally missed that)

**Comment by mvysny** [comment] 2018-11-08 18:37
Hi, thanks for your message! It is actually possible to attach a message to any entry: just long-touch any entry and select "Tag Entry" from the upper-right overflow menu. You can tag an entry (or multiple entries at once) with a color, or a text, or a color and a text ;)

Please let me know if this solves your issue, and thanks for subscribing! :)

**Comment by ckaden** [comment] 2018-11-08 19:22
Thanks for your quick reply!

Oh, I see. I never touched 'Tag Entries' because I expect a tag only system behind it (=reusable, short words), not free and longer text as is used for comments. Using 'Tag Entries' as comments feels like diverting it from its intended use.  I don't think a typical tag system is useful for Aedict at all, as those informations should be already supplied by the dictionary itself. Building up tags is quite a mammoth task after all.

So my feature request for 'Custom notes' as explained in my first post still stands. 'Tag Entries' is not a proper substitute imho.

**Comment by mvysny** [comment] 2018-11-13 08:31
Hi, the tag system is designed to attach any notice you wish to each entry. The notice may be potentially long. It is shown in its entirety only in the Entry Details screen - in the list of entries only the first line or a first couple of characters are shown. Therefore I believe you can use it even for your use-case.

I apologize but I'm extremely preoccupied these days, so it takes a lot of time to get to Aedict development nowadays :(

**Comment by ckaden** [comment] 2018-11-16 11:33
For me it's not visible on the Entry Details, just a hint in case of the tag symbol that there a tag attached. I have to click it first to see it.

If it would be shown under the meanings with a edit button next to it (so it's not instantly in edit mode), that would be perfect.

Screenshot attached.

![screenshot-photos google com-2018 11 16-12-31-15](https://user-images.githubusercontent.com/38889357/48619119-c0e16600-e99b-11e8-81a0-047dba22a7e3.jpg)

**Comment by mvysny** [comment] 2018-11-16 12:31
Ah, right! That makes sense, I'll implement this. Thanks! ;)

**Comment by mvysny** [comment] 2018-11-23 19:32
Hmm, I can see the text "This is a test!" right below the kanjis:
![tag](https://user-images.githubusercontent.com/254091/48958381-40a49d00-ef67-11e8-934b-a29282bee78c.png)

**Comment by ckaden** [comment] 2018-11-24 15:30
Oh my, you're right! Didn't notice it being there.

I made a test with a longer comment and it doesn't look good when longer. Additionally, it's being cut off after a certain length.

Imho it should still be moved to below the meanings and be displayed in full.

![screenshot_20181124-162727](https://user-images.githubusercontent.com/38889357/48969938-2077eb00-f006-11e8-942a-ba9f0b5049a8.png)

**Comment by mvysny** [comment] 2018-11-27 08:37
Hi! The problem is that there could be multiple readings/meanings of the same word, and I need to match a proper tag to both of those readings. I have fixed the bug and the entire tag should now be shown:
![device-2018-11-27-103656](https://user-images.githubusercontent.com/254091/49068827-64e6cf00-f230-11e8-90e9-0b2bd7df07a6.png)

**Comment by mvysny** [comment] 2018-11-28 17:30
Fixed in Aedict 3.50.8

**Closed by mvysny** 2018-11-28 17:30 UTC
Labels: enhancement, user feedback needed
