### ISSUE TITLE
AEDICT fails to write backup to external SD card location

### ISSUE THREAD

**Issue by sanada1615** [mvysny/aedict#703] opened 2016-10-20 05:20 UTC
I'm using MIUI 8's version of Android, and a Xiaomi Redmi Note 3. It seems AEDICT is unable to write to my SD card (I get a "cannot write to SD card" message), when I try to backup to it.

**Comment by mvysny** [comment] 2016-10-21 06:47
I apologize for the inconvenience. This is weird - Aedict (or, rather, Google Play) should have asked for write rights to the SD Card. Do any other apps also have trouble writing to the SD Card as well?
Unfortunately it is next to impossible to fix this issue as I do not have access to the Xiaomi Redmi Note 3 device. Yet, I can have a look: can you please try to find the stacktrace in your device log? Please see http://aedict.eu/faq.html "Aedict 3 log" for more details.

**Comment by mvysny** [comment] 2017-01-28 10:18
Also, please check in your phone's security settings whether Aedict is allowed to access the SD Card. Sometimes phone revokes app rights for no apparent reason.

**Comment by mvysny** [comment] 2017-01-28 10:20
Closing since i can't reproduce this issue, please reopen if there is more information.

**Closed by mvysny** 2017-01-28 10:20 UTC
Labels: bug, user feedback needed
