### ISSUE TITLE
Kanji drawing search after switch to open app fails, requires app close

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#547] opened 2015-08-22 12:32 UTC
If you switch to Aedict from some other app (Anki in my case) while Aedict was already instantiated, the stroke kanji search fails with the following message: Failed to find kanjis, a

**Comment by kcroker** [comment] 2015-08-22 12:32
Failed to find kanjis: android.os.DeadObjectException

**Comment by mvysny** [comment] 2015-08-23 20:31
Thank you for letting me know, and I apologize for this behavior. I will try to reproduce the issue myself, please stay tuned.

**Comment by kcroker** [comment] 2015-08-23 22:55
The issue seems to have gone away with a dictionary update, so that may be
a clue :)

Again, amazing program!  I bought the stroke drawing program even though I
don't need it, so that I could pay you in some way since you refuse paypal
donations!

**Comment by kcroker** [comment] 2015-08-24 12:50
The bug persists even with up to date dictionaries: newest Nexus 5 stock
Android.
On Aug 23, 2015 4:31 PM, "Martin Vysny" <notifications@github.com> wrote:

Thank you for letting me know, and I apologize for this behavior. I will
try to reproduce the issue myself, please stay tuned.

—
Reply to this email directly or view it on GitHub
<https://github.com/mvysny/aedict/issues/547#issuecomment-133926962>.

**Comment by mvysny** [comment] 2015-08-24 13:20
Well, I do not reject donations per se ;) I will gladly accept the donations via PayPal, my mail address is vysny@baka.sk. Any support is very appreciated.

**Comment by mvysny** [comment] 2015-08-25 05:35
Unfortunately I cannot reproduce this issue myself. I can try to perform a blind fix, but first I would perhaps try to reproduce the issue. Can you please describe in more depth, how exactly are you switching to Aedict from some other app? I tried both sharing selected text to Aedict and activating the persistent notification message, but I get no DeadObjectException. Perhaps the KanjiPadExt service is killed by your phone during the drawing lookup, because of low memory? What kind of phone do you have, and how much memory does it have?

**Comment by mvysny** [comment] 2015-08-25 12:11
Aha! Reproduced ;) If the search service is killed, the client will start failing with DeadObjectException.

**Comment by mvysny** [comment] 2015-08-25 13:13
Fixed in Aedict 3.32, please reopen if Aedict fails again.

**Closed by mvysny** 2015-08-25 13:13 UTC
Labels: bug
