### ISSUE TITLE
Aedict "crashes" as soon as I click on a dictionary entry. 

### ISSUE THREAD

**Issue by LsFired** [mvysny/aedict#817] opened 2018-01-08 13:28 UTC
Hello. I originally had Aedict for free on Amazon Underground, but it was so good I decided to buy it for my Fire tablet! I have also bought it for my Android phone. However, with the latest update, my Fire tablet will not allow me to view any dictionary entry for more than a second before crashing! Or sometimes it will take me to the previous screen. I have included a video to show you. https://youtu.be/hurSzSjEEWw

**Comment by mvysny** [comment] 2018-01-08 13:45
Thank you for letting me know, and I apologize for the crash :( Also thank you for taking the time and shooting the video.

I can not reproduce the crash on my phone, but I do have a couple of crash reports reported by the built-in crash report mechanism. I believe that this particular crash has been caused by me, using too new Android API unintentionally.

I have already fixed the crash; I plan to fix other critical things as well and publish updated Aedict in 1-2 days. Please stay tuned :)

**Comment by mvysny** [comment] 2018-01-08 13:46
Fixed in Aedict 3.47.

**Closed by mvysny** 2018-01-08 13:46 UTC
Labels: bug
