### ISSUE TITLE
Unable to export to ankidroid

### ISSUE THREAD

**Issue by laxa88** [mvysny/aedict#782] opened 2017-07-23 08:49 UTC
Not sure if this is an isolated issue, but I'll just open it here anyway:

Tried using aedict + ankidroid on Samsung Galaxy S8+ yesterday. I was unable to export any cards from aedict to ankidroid (via both swipe shortcut and via menu). Is there any step I am possibly missing, or is this a potential bug?

edit: i tried to set the app permission in the settings but it always auto-toggle off. if i try to toggle it on and off, it will say something "this app is designed for an older version of android". im using nougat.

edit2: export still works on my samsung note 4, on marshmallow.

**Comment by pjcuy** [comment] 2017-07-28 04:49
I'm having the same issue on Android 6.0.1.

**Comment by mvysny** [comment] 2017-07-28 05:28
Hmm, sounds like a bug related to Samsung S8 and custom permissions. AnkiDroid currently requires Aedict to have an AnkiDroid-custom permission to be able to export data; it seems that Samsung s8 is not granting it. Perhaps there are others with the same issue- can you please ask on Ankidroid forums?

**Comment by pjcuy** [comment] 2017-07-28 06:08
Oh, I forgot to mention that I'm using a Nexus 5X.

**Comment by mvysny** [comment] 2017-07-28 15:49
This is most probably a duplicate of #723 . Closing as duplicate, please reopen if this is not the case. Please make sure to read the Ankidroid bug referenced from the above-mentioned bug as it contains more info.

**Closed by mvysny** 2017-07-28 15:49 UTC
Labels: bug

**Comment by laxa88** [comment] 2017-07-31 17:44
@mvysny thanks for the link! i reinstalled aedict as suggested and now it works. don't know what happened previously, but glad it was quick fixable :)
