### ISSUE TITLE
Verb inflection search

### ISSUE THREAD

**Issue by Spanja** [mvysny/aedict#862] opened 2019-02-17 05:24 UTC
Hello,

I did a search with the keyword いらない and I get verbs results that doesn't contain this search.
For example, the negative form of いる is いない, and not いらない.

![screenshot_20190217-111820](https://user-images.githubusercontent.com/626863/52908771-a4690880-32bf-11e9-86d1-259aab4707e2.png)

**Comment by mvysny** [comment] 2019-02-20 09:40
iru as a godan inflects to iranai, while iru as ichidan inflects to inai. However, it's true that when Aedict deinflects iranai to iru, it should only match godan verbs; deinflections from inai to iru should then only match ichidan verbs. This change is not easy to fix unfortunately, but I'll try my best.

**Comment by mvysny** [comment] 2019-02-20 11:43
The problem is that I can't establish a rule that -enai deinflects to -eru for ichidan only, since for example irenai deinflects to ireru which deinflects to iru, possibly both to godan and ichidan. I can however for starters mark -anai as godan since ichidan verb always ends with -eru or -iru. That should do the trick for iranai; -inai can deinflect only to ichidan which should to the trick for inai -> iru.

**Comment by mvysny** [comment] 2019-02-20 14:20
Fixed in 3.50.11

**Closed by mvysny** 2019-02-20 14:20 UTC
Labels: bug

**Comment by Spanja** [comment] 2019-02-24 08:42
Hello Martin,

I get another bug when i'm searching 起きましょう, I get strange results
BTW, notice the 起きまsる bug

Does that fix this too ?

![screenshot_20190224-173238](https://user-images.githubusercontent.com/626863/53297057-32fafe00-385b-11e9-854a-0052c8bff01c.png)

**Comment by mvysny** [comment] 2019-02-24 08:47
The deinflection to  起きまsる is definitely a bug in aedict - can you please create a new bug report for that? I think the weird results could be a consequence of this weird deinflection.

**Comment by Spanja** [comment] 2019-02-24 09:25
Sure !
